name: 🚨 Validate PR Template

on:
  pull_request_target:
    types: [opened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-pr-template:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR Body
        id: validate
        run: |
          echo "🔍 Validating PR template..."
          PR_BODY=$(jq -r .pull_request.body < "$GITHUB_EVENT_PATH")

          # Required sections
          REQUIRED_HEADERS=("## Summary" "## Description" "## Images" "## Issue Addressed" "## Prerequisites")
          MISSING_HEADERS=()
          for header in "${REQUIRED_HEADERS[@]}"; do
            if ! echo "$PR_BODY" | grep -q "$header"; then
              MISSING_HEADERS+=("$header")
            fi
          done

          # Closes issue check
          # if ! echo "$PR_BODY" | grep -Eiq '(^|\n)-?\s*Closes\s+#\d+'; then
          #   MISSING_HEADERS+=("Valid 'Closes #<issue_number>' line")
          # fi

          # CONTRIBUTING checkbox check
          if ! echo "$PR_BODY" | grep -Eiq '\- \[x\] .*CONTRIBUTING'; then
            MISSING_HEADERS+=("Checked 'Have you followed all the CONTRIBUTING GUIDELINES?' box")
          fi

          if [ ${#MISSING_HEADERS[@]} -gt 0 ]; then
            echo "❌ PR template validation failed."
            echo "result=failure" >> $GITHUB_OUTPUT
            echo "MISSING_HEADERS=${MISSING_HEADERS[*]}" >> $GITHUB_ENV
          else
            echo "✅ PR template passed validation."
            echo "result=success" >> $GITHUB_OUTPUT
          fi

      - name: Debug PR Body
        run: |
          echo "$PR_BODY"

      - name: Comment and Close PR if Invalid
        if: steps.validate.outputs.result == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" -R "${{ github.repository }}" --body $'❌ **PR Template Validation Failed**\n\nYour PR is missing required fields:\n\n${{ env.MISSING_HEADERS }}\n\nPlease update your PR to follow the required format: https://github.com/upes-open/OSoc-25-Giglance/blob/main/.github/pull_request_template.md\n\nThis PR is being closed automatically.'
          gh pr edit "${{ github.event.pull_request.number }}" -R "${{ github.repository }}" --add-label "PR Template Invalid"
          gh pr close "${{ github.event.pull_request.number }}" -R "${{ github.repository }}"

      - name: PR is valid
        if: steps.validate.outputs.result == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "✅ Thanks @${{ github.actor }}! Your PR description is formatted correctly!"
          gh pr edit ${{ github.event.pull_request.number }} --remove-label "PR Template Invalid"
          gh pr reopen ${{ github.event.pull_request.number }}
